name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: read-all
jobs:
  build:
    name: Build (OS = ${{matrix.os}}, Args = 'lll${{matrix.args}}')
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 'Build "lll${{matrix.args}}" (Ubuntu)'
      if: matrix.os=='ubuntu-latest'
      run: python src/_build/main.py --verbose${{matrix.args}}
    - name: Setup Windows Environment
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os=='windows-latest'
    - name: 'Build "lll${{matrix.args}}" (Windows)'
      if: matrix.os=='windows-latest'
      run: python src/_build/main.py --verbose${{matrix.args}}
      shell: cmd
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        args:
          - ''
          - ' --release'
          - ' --standalone'
          - ' --standalone --release'
    timeout-minutes: 5
